'use strict';
const API_BASE=window.AVIATOR_API_BASE||'http://localhost:10000',q=id=>document.getElementById(id),api=q('api'),status=q('status');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const mul=v=>v==null?'—':Number(v).toFixed(2)+'x',pct=v=>v==null?'—':Number(v).toFixed(2)+'%';
async function get(path){const r=await fetch(API_BASE+path);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function show(d){if(!d?.ok)throw Error('Invalid API response');api.textContent='API ONLINE';api.className='on';q('action').textContent=d.signal.action;q('action').className='action '+d.signal.action.toLowerCase();q('score').textContent=d.signal.score??'—';q('confidence').textContent=d.signal.confidence+'%';q('risk').textContent=d.signal.risk;q('reasons').innerHTML=(d.signal.reasons||[]).map(x=>'<p>• '+esc(x)+'</p>').join('');q('prev').textContent=d.previousRound?`#${d.previousRound.roundId} ${mul(d.previousRound.multiplier)}`:'—';q('latest').textContent=d.latestRound?`#${d.latestRound.roundId} ${mul(d.latestRound.multiplier)}`:'—';q('next').textContent=d.nextRound?'#'+d.nextRound.roundId:'—';q('entry').textContent=d.entry.entryTime||'Next round #'+d.entry.entryRound;const s=d.analysis.summary,f=d.analysis.recent.features,b=d.model.backtest;q('samples').textContent=s.samples;q('summary').innerHTML=[['Min',mul(s.min)],['Median',mul(s.median)],['Mean',mul(s.mean)],['Max',mul(s.max)]].map(x=>`<p>${x[0]} <strong>${x[1]}</strong></p>`).join('');q('recent').innerHTML=[['Window',f.recentWindow],['Recent mean',mul(f.recentMean)],['>=2x rate',pct(f.recentRates.atLeast2)],['>=3x rate',pct(f.recentRates.atLeast3)],['Low streak',f.lowStreak],['Very-low streak',f.veryLowStreak]].map(x=>`<p>${x[0]} <strong>${x[1]}</strong></p>`).join('');q('hit').textContent=b.samples?pct(b.hitRate):'—';q('bt').innerHTML=[['Samples',b.samples],['Hits',b.hits],['Misses',b.misses],['Coverage',pct(b.coverage/100)]].map(x=>`<p>${x[0]} <strong>${x[1]}</strong></p>`).join('');q('table').innerHTML=d.analysis.recent.rounds.slice().reverse().map(r=>`<div class="row"><span>#${r.roundId}</span><strong>${mul(r.multiplier)}</strong><span>${r.multiplier>=10?'EXTREME':r.multiplier>=3?'HIGH':r.multiplier>=2?'TARGET+':r.multiplier<1.2?'LOW':'MID'}</span></div>`).join('');q('time').textContent=d.analyzedAt?new Date(d.analyzedAt).toLocaleString():'—';status.textContent='V'+d.version+' analysis loaded.'}
async function run(path,msg,render=true){try{status.textContent=msg;const d=await get(path);if(render)show(d);else{api.textContent='API ONLINE';api.className='on';status.textContent='Backtest loaded.'}}catch(e){api.textContent='API OFFLINE';api.className='off';status.textContent=e.message}}
q('analyze').onclick=()=>run('/api/analyze','Analyzing...');q('backtest').onclick=()=>run('/api/backtest','Running backtest...',false);q('history').onclick=async()=>{try{const d=await get('/api/history');q('table').innerHTML=d.rounds.slice().reverse().map(r=>`<div class="row"><span>#${r.roundId}</span><strong>${mul(r.multiplier)}</strong><span>HISTORICAL</span></div>`).join('');status.textContent=d.total+' rounds loaded.'}catch(e){status.textContent=e.message}};
run('/api/analyze','Connecting to API...');
