'use strict';
const express=require('express'); const cors=require('cors');
const app=express(); const PORT=process.env.PORT||10000; const VERSION='V1.0';
app.use(cors()); app.use(express.json());
const RAW_ROUNDS=[1.64,1.34,1.01,7.39,1.24,3.91,1.07,1.05,2.20,1.09,1.36,1.38,12.40,14.02,1.07,1.81,1.84,2.29,1.71,1.00,5.75,2.31,1.01,1.06,9.70,238.30,1.29,1.18,15.16,1.13,1.06,2.14,2.00,1.07,1.28,1.36,1.31,10.64,1.14,5.44,30.64,7.88,1.01,1.82,1.54,28.07,1.28,2.22,1.11,4.01,1.72,1.00,1.04,2.42,3.32,4.45,10.53,3.81];
const ROUNDS=RAW_ROUNDS.map((multiplier,i)=>({roundId:i+1,multiplier,timestamp:null,source:'initial-dataset'}));
const CFG={minHistory:20,target:2,lookback:12,threshold:68,minBacktest:12};
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function median(a){if(!a.length)return 0;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)); const pct=n=>+(n*100).toFixed(2);
function streak(a,p){let n=0;for(let i=a.length-1;i>=0&&p(a[i]);i--)n++;return n}
function longest(a,p){let best=0,n=0;for(const x of a){n=p(x)?n+1:0;best=Math.max(best,n)}return best}
function summary(a){const c=x=>a.filter(x).length;return{samples:a.length,min:+Math.min(...a).toFixed(2),max:+Math.max(...a).toFixed(2),mean:+avg(a).toFixed(2),median:+median(a).toFixed(2),rates:{below1_2:pct(c(v=>v<1.2)/a.length),below1_5:pct(c(v=>v<1.5)/a.length),atLeast2:pct(c(v=>v>=2)/a.length),atLeast3:pct(c(v=>v>=3)/a.length),atLeast5:pct(c(v=>v>=5)/a.length),atLeast10:pct(c(v=>v>=10)/a.length)},longestStreaks:{below1_2:longest(a,v=>v<1.2),below1_5:longest(a,v=>v<1.5),atLeast2:longest(a,v=>v>=2)}}}
function features(a){const r=a.slice(-CFG.lookback),last=a.at(-1),prev=a.at(-2);return{sampleSize:a.length,lastMultiplier:+last.toFixed(2),previousMultiplier:prev==null?null:+prev.toFixed(2),recentWindow:r.length,recentMean:+avg(r).toFixed(2),recentMedian:+median(r).toFixed(2),recentRates:{below1_2:pct(r.filter(v=>v<1.2).length/r.length),below1_5:pct(r.filter(v=>v<1.5).length/r.length),atLeast2:pct(r.filter(v=>v>=2).length/r.length),atLeast3:pct(r.filter(v=>v>=3).length/r.length),atLeast5:pct(r.filter(v=>v>=5).length/r.length)},lowStreak:streak(r,v=>v<1.5),veryLowStreak:streak(r,v=>v<1.2)}}
function rawScore(f){let s=50;if(f.recentRates.atLeast2>=33)s+=8;else if(f.recentRates.atLeast2<=16)s-=6;if(f.veryLowStreak>=3)s+=7;if(f.lowStreak>=4)s+=5;if(f.lastMultiplier>=3)s-=5;if(f.lastMultiplier<1.2)s+=4;return clamp(Math.round(s),0,100)}
function backtest(){const rows=[];for(let i=CFG.minHistory;i<ROUNDS.length;i++){const h=ROUNDS.slice(0,i).map(r=>r.multiplier),f=features(h),s=rawScore(f);if(s>=CFG.threshold)rows.push({targetRound:i+1,score:s,actualMultiplier:ROUNDS[i].multiplier,hit:ROUNDS[i].multiplier>=CFG.target})}const hits=rows.filter(x=>x.hit).length,misses=rows.length-hits;return{targetMultiplier:CFG.target,samples:rows.length,hits,misses,hitRate:rows.length?+(hits/rows.length*100).toFixed(2):0,coverage:+(rows.length/(ROUNDS.length-CFG.minHistory)*100).toFixed(2),rows:rows.slice(-20)}}
function analysis(){const a=RAW_ROUNDS,f=features(a),bt=backtest();let score=rawScore(f),reasons=[];if(f.recentRates.atLeast2>=33)reasons.push('Recent >=2x rate is relatively strong.');else if(f.recentRates.atLeast2<=16)reasons.push('Recent >=2x rate is weak.');if(f.veryLowStreak>=3){score+=7;reasons.push('A very-low streak is present.')}if(f.lowStreak>=4){score+=5;reasons.push('A low-multiplier streak is present.')}if(f.lastMultiplier>=3){score-=5;reasons.push('Latest round was elevated; model avoids chasing immediately.')}if(f.lastMultiplier<1.2){score+=4;reasons.push('Latest round was very low.')}if(bt.samples>=CFG.minBacktest){if(bt.hitRate>=50){score+=10;reasons.push('Walk-forward backtest is above 50% on qualifying samples.')}else if(bt.hitRate<40){score-=10;reasons.push('Walk-forward backtest is below 40% on qualifying samples.')}}score=clamp(Math.round(score),0,100);const action=score>=CFG.threshold&&bt.samples>=CFG.minBacktest?'ENTER':'WAIT';return{ok:true,version:VERSION,analyzedAt:new Date().toISOString(),previousRound:ROUNDS.at(-2),latestRound:ROUNDS.at(-1),nextRound:{roundId:ROUNDS.length+1,multiplier:null,timestamp:null,source:'awaiting-live-round'},analysis:{dataset:'58-round initial dataset',summary:summary(a),recent:{lookback:CFG.lookback,rounds:ROUNDS.slice(-CFG.lookback),features:f}},signal:{action,confidence:clamp(Math.round(40+Math.abs(score-50)*.85),40,82),score,targetMultiplier:CFG.target,risk:action==='ENTER'?'HIGH':'LOW',reasons},entry:{entryRound:ROUNDS.length+1,entryTime:null,countdownSeconds:null,rule:'Wait for the next round; V1.0 has no live round clock.'},model:{name:'Aviator V1 Evidence Model',architecture:['collect','analyze','backtest','score','signal'],target:'next round >= 2.00x',minimumHistory:CFG.minHistory,backtest:bt,disclaimer:'Historical patterns do not guarantee the next multiplier.'}}}
app.get('/',(_,res)=>res.json({ok:true,name:'AVIATOR AI PREDICTOR',version:VERSION,message:'Use /api/analyze, /api/history, /api/status or /api/backtest.'}));
app.get('/api/status',(_,res)=>res.json({ok:true,version:VERSION,source:'initial-dataset',dataset:{rounds:ROUNDS.length,firstRound:ROUNDS[0],lastRound:ROUNDS.at(-1)},architecture:['collect','analyze','backtest','score','signal'],liveFeed:false,ready:true}));
app.get('/api/history',(_,res)=>res.json({ok:true,version:VERSION,rounds:ROUNDS,total:ROUNDS.length,source:'initial-dataset'}));
app.get('/api/analyze',(_,res)=>res.json(analysis()));
app.get('/api/backtest',(_,res)=>{const x=analysis();res.json({...x,signal:{action:'BACKTEST ONLY',confidence:0,score:null,targetMultiplier:CFG.target,risk:'N/A',reasons:['Historical walk-forward results only.']}})});
app.listen(PORT,()=>console.log(`AVIATOR AI PREDICTOR ${VERSION} listening on ${PORT}`));
